import { access, readFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { spawnSync } from 'node:child_process';
const root = resolve(import.meta.dirname, '..');
const run = (args) => { const r = spawnSync(process.execPath, args, { cwd: root, stdio: 'inherit' }); if (r.status !== 0) process.exit(r.status ?? 1); };
run(['scripts/build.mjs']);
run(['scripts/audit.mjs']);
const required = ['dist/index.html', 'dist/styles.css', 'dist/tailwind.css', 'dist/app.js', 'dist/_headers', 'dist/manus-routes.json', 'functions/[[path]].ts'];
for (const file of required) await access(resolve(root, file));
const html = await readFile(resolve(root, 'dist/index.html'), 'utf8');
for (const marker of ['id="works"', 'id="approach"', 'id="about"', 'github.com/inumabu', 'Hono', 'Cloudflare Workers', 'Yanagi', 'MabuBot', 'Mojule', 'Aurora Sauce Language']) if (!html.includes(marker)) throw new Error(`Missing marker: ${marker}`);
const tailwind = await readFile(resolve(root, 'dist/tailwind.css'), 'utf8');
if (!tailwind.includes('--color-lime') && !tailwind.includes('dfff4f')) throw new Error('Tailwind theme was not generated');
console.log('✅ Portfolio build, Tailwind CSS, and content verification passed');
